package spielefachhandel;
public enum Screen {
    STARTBILDSCHIRM, HAUPTMENUE, TABELLENAUSWAHL, KUNDEAUSGABE, RECHNUNGAUSGABE, POSITIONAUSGABE, SPIELAUSGABE,
    KUNDESUCHEN, RECHNUNGSUCHEN, POSITIONSUCHEN, SPIELSUCHEN, KUNDE_EINFUEGEN, RECHNUNG_EINFUEGEN, POSITION_EINFUEGEN, SPIEL_EINFUEGEN;
}